# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  digitalmenu:
    image: digitalmenu
    build:
      context: .
      dockerfile: Server/DigitalMenu/DigitalMenu/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5235:5235
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
